import { StyleSheet } from "react-native";

const palette = {
  background: "#F5FBF7",
  surface: "#FFFFFF",
  surfaceSoft: "#F7FCF9",
  surfaceMuted: "#EDF7F0",
  border: "#DDEDE3",
  borderStrong: "#C8DDCF",
  textPrimary: "#0F172A",
  textSecondary: "#475569",
  textTertiary: "#94A3B8",
  accent: "#60C28E",
  accentStrong: "#3E9E6C",
  accentSoft: "#EAF8F0",
  accentSoftBorder: "#C7E7D3",
  success: "#34D399",
  pink: "#A8E1C0",
  danger: "#EF4444",
  shadow: "#163127",
};

export const workspaceTheme = {
  icon: palette.accent,
  iconMuted: palette.textSecondary,
  placeholder: palette.textTertiary,
  iconOnAccent: "#FFFFFF",
  danger: palette.danger,
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  root: {
    flex: 1,
    position: "relative",
    overflow: "hidden",
  },
  backgroundOrbTop: {
    position: "absolute",
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: "rgba(96,194,142,0.12)",
    top: -118,
    right: -78,
  },
  backgroundOrbBottom: {
    position: "absolute",
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: "rgba(168,225,192,0.12)",
    bottom: -126,
    left: -82,
  },
  workspaceLayer: {
    flex: 1,
  },
  workspaceKeyboard: {
    flex: 1,
  },
  workspaceCard: {
    flex: 1,
    marginHorizontal: 0,
    marginTop: 0,
    marginBottom: 0,
    borderRadius: 34,
    backgroundColor: "transparent",
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 8,
    borderWidth: 0,
    borderColor: "transparent",
    shadowColor: palette.shadow,
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  workspaceHeader: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginTop: 4,
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.92)",
    borderWidth: 1,
    borderColor: palette.border,
    overflow: "hidden",
    zIndex: 4,
  },
  workspaceHeaderTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  workspaceToolbar: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 8,
  },
  workspaceTitleBlock: {
    flex: 1,
    minHeight: 64,
  },
  spaceInfoCard: {
    flex: 1,
    borderRadius: 24,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 14,
    shadowColor: palette.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  workspaceTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  spaceInfoTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  workspaceEyebrow: {
    color: palette.textTertiary,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  workspaceTitle: {
    color: palette.textPrimary,
    fontSize: 23,
    fontWeight: "800",
    lineHeight: 28,
    flexShrink: 1,
  },
  workspaceDescription: {
    marginTop: 8,
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 21,
    maxWidth: 280,
  },
  spaceMetaRow: {
    marginTop: 9,
    maxWidth: "100%",
  },
  spaceInfoBottomRow: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  spaceHero: {
    position: "relative",
    paddingTop: 4,
    paddingBottom: 4,
    zIndex: 22,
    elevation: 12,
    overflow: "visible",
  },
  spaceHeroTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    overflow: "visible",
  },
  spaceHeroHeaderBlock: {
    alignItems: "flex-start",
  },
  spaceHeroInfo: {
    flex: 1,
    minWidth: 0,
  },
  spaceTitleInlineRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    maxWidth: "100%",
  },
  spaceHeroTitle: {
    color: palette.textPrimary,
    fontSize: 30,
    fontWeight: "800",
    lineHeight: 38,
    flexShrink: 1,
  },
  spaceHeroTitleMedium: {
    fontSize: 27,
    lineHeight: 34,
  },
  spaceHeroTitleCompact: {
    fontSize: 24,
    lineHeight: 30,
  },
  spaceHeroSubtitle: {
    marginTop: 6,
    color: palette.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  renameInlineButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.accentSoftBorder,
  },
  spaceCodePill: {
    width: "100%",
    marginTop: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: palette.surface,
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.2,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: palette.accentSoftBorder,
  },
  renameIconButton: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.accentSoftBorder,
  },
  memberRow: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  memberStack: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 2,
    flexShrink: 0,
  },
  memberAvatarWrap: {
    borderWidth: 2,
    borderColor: palette.surface,
    borderRadius: 999,
    shadowColor: palette.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  heroMemberSection: {
    marginTop: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  memberLabel: {
    color: palette.textSecondary,
    fontSize: 13,
    fontWeight: "700",
  },
  heroActionRow: {
    marginTop: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    width: "100%",
  },
  heroPrimaryAction: {
    flex: 1,
    minHeight: 60,
    borderRadius: 18,
    backgroundColor: palette.accent,
    borderWidth: 1,
    borderColor: palette.accent,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: palette.accent,
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  heroPrimaryActionText: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "800",
  },
  heroSecondaryAction: {
    minHeight: 60,
    minWidth: 120,
    borderRadius: 18,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: palette.shadow,
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  heroSecondaryActionText: {
    color: palette.textPrimary,
    fontSize: 16,
    fontWeight: "700",
  },
  headerActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 0,
    borderRadius: 999,
    backgroundColor: "transparent",
    borderWidth: 0,
    zIndex: 18,
  },
  headerActionRowCompact: {
    gap: 8,
  },
  toolbarActions: {
    alignItems: "flex-end",
    paddingTop: 6,
  },
  workspaceActionShelf: {
    marginTop: 12,
    marginBottom: 2,
    alignItems: "flex-end",
  },
  headerActionButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: palette.surfaceSoft,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: palette.accentSoftBorder,
  },
  headerActionButtonCompact: {
    minHeight: 42,
    borderRadius: 14,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    shadowColor: palette.shadow,
    shadowOpacity: 0.07,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  headerActionButtonCompactPrimary: {
    backgroundColor: palette.accent,
    borderWidth: 1,
    borderColor: palette.accent,
    minWidth: 84,
  },
  headerActionButtonCompactSecondary: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    minWidth: 78,
  },
  headerActionButtonCompactText: {
    fontSize: 13,
    fontWeight: "800",
  },
  headerActionButtonCompactTextPrimary: {
    color: "#FFFFFF",
  },
  headerActionButtonCompactTextSecondary: {
    color: palette.textPrimary,
  },
  headerMenuWrap: {
    position: "relative",
    zIndex: 42,
    elevation: 28,
  },
  quickMenu: {
    position: "absolute",
    top: 48,
    right: 0,
    width: 156,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.985)",
    padding: 7,
    gap: 5,
    borderWidth: 1,
    borderColor: palette.accentSoftBorder,
    shadowColor: palette.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 28,
    zIndex: 52,
  },
  quickMenuCompact: {
    top: 44,
  },
  quickMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderRadius: 12,
    backgroundColor: palette.surfaceMuted,
    paddingHorizontal: 9,
    paddingVertical: 8,
  },
  quickMenuText: {
    color: palette.textPrimary,
    fontSize: 12,
    fontWeight: "700",
  },
  quickMenuDangerText: {
    color: palette.danger,
  },
  feedScroll: {
    flex: 1,
    marginTop: 8,
  },
  feedContent: {
    paddingBottom: 20,
    gap: 16,
  },
  feedActionRow: {
    alignItems: "flex-end",
    marginBottom: 2,
    zIndex: 4,
  },
  compactHeader: {
    position: "absolute",
    top: 10,
    left: 16,
    right: 16,
    zIndex: 12,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderWidth: 1,
    borderColor: palette.accentSoftBorder,
    shadowColor: palette.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  compactHeaderContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  compactHeaderTitle: {
    flex: 1,
    minWidth: 0,
    color: palette.textPrimary,
    fontSize: 18,
    fontWeight: "800",
  },
  feedHeadingRow: {
    marginTop: 6,
    marginBottom: 2,
    alignItems: "center",
  },
  feedHeading: {
    color: palette.textPrimary,
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: 1,
  },
  heroEmptyCard: {
    borderRadius: 28,
    backgroundColor: "rgba(255,255,255,0.9)",
    paddingHorizontal: 20,
    paddingVertical: 22,
    alignItems: "flex-start",
    gap: 12,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: palette.shadow,
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 4,
  },
  emptyLaunchCard: {
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.92)",
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: palette.accentSoftBorder,
    shadowColor: palette.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  emptyLaunchButton: {
    borderRadius: 20,
    minHeight: 56,
    alignItems: "center",
    justifyContent: "center",
  },
  heroEmptyTitle: {
    color: palette.textPrimary,
    fontSize: 22,
    fontWeight: "800",
  },
  heroEmptyText: {
    color: palette.textSecondary,
    fontSize: 14,
    lineHeight: 22,
  },
  emptyActionRow: {
    marginTop: 4,
    flexDirection: "row",
    gap: 10,
  },
  emptyPrimaryButton: {
    borderRadius: 16,
    backgroundColor: palette.accent,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: palette.accent,
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  emptyPrimaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  emptyGhostButton: {
    borderRadius: 16,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.accentSoftBorder,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  emptyGhostButtonText: {
    color: palette.textSecondary,
    fontSize: 14,
    fontWeight: "700",
  },
  postCard: {
    borderRadius: 30,
    backgroundColor: palette.surface,
    padding: 18,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: palette.shadow,
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 5,
  },
  postHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  postAuthorWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  postAuthorTextWrap: {
    flex: 1,
  },
  postAuthor: {
    color: palette.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  postMeta: {
    marginTop: 3,
    color: palette.textTertiary,
    fontSize: 12,
  },
  postEditButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    backgroundColor: palette.surface,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: palette.border,
  },
  postEditButtonText: {
    color: palette.accentStrong,
    fontSize: 12,
    fontWeight: "700",
  },
  postText: {
    marginTop: 14,
    color: palette.textSecondary,
    fontSize: 14,
    lineHeight: 22,
  },
  postImageRow: {
    marginTop: 12,
  },
  feedImage: {
    borderRadius: 18,
    marginRight: 10,
    backgroundColor: palette.surfaceMuted,
  },
  feedImageLandscape: {
    width: 250,
  },
  feedImagePortrait: {
    height: 280,
  },
  commentList: {
    marginTop: 14,
    gap: 8,
  },
  commentEmptyText: {
    color: palette.textTertiary,
    fontSize: 12,
  },
  commentCard: {
    borderRadius: 14,
    backgroundColor: palette.surfaceSoft,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: palette.border,
  },
  commentAuthor: {
    color: palette.accentStrong,
    fontSize: 12,
    fontWeight: "800",
  },
  commentText: {
    marginTop: 4,
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  commentRow: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 10,
  },
  commentInput: {
    flex: 1,
    minHeight: 46,
    maxHeight: 92,
    borderRadius: 16,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: palette.textPrimary,
  },
  commentButton: {
    borderRadius: 16,
    backgroundColor: palette.accent,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: palette.accent,
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  commentButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
  },
  workspaceDimLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(15,23,42,0.06)",
    borderRadius: 0,
  },
  sidebarBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 8,
  },
  sidebarDockShell: {
    position: "absolute",
    left: -10,
    top: 0,
    bottom: 0,
    zIndex: 16,
    elevation: 16,
    justifyContent: "center",
  },
  sidebarDockCard: {
    width: 42,
    height: 144,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.78)",
    borderWidth: 1,
    borderColor: palette.border,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    shadowColor: palette.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  sidebarDockCardActive: {
    backgroundColor: palette.accentStrong,
    borderColor: palette.accentStrong,
  },
  sidebarDockProfileButton: {
    marginTop: 14,
  },
  sidebarDockSpaceBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.border,
  },
  sidebarDockSpaceBadgeActive: {
    backgroundColor: palette.accentSoft,
    borderColor: palette.accentSoftBorder,
  },
  sidebarDockSpaceBadgeText: {
    color: palette.accentStrong,
    fontSize: 13,
    fontWeight: "800",
  },
  sidebarDockSpaceBadgeTextActive: {
    color: palette.accentStrong,
  },
  sidebarDockSpacer: {
    flex: 1,
  },
  sidebarDockHint: {
    color: palette.textSecondary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.2,
    width: 72,
    textAlign: "center",
    transform: [{ rotate: "-90deg" }],
    marginTop: 4,
  },
  sidebarShell: {
    position: "absolute",
    top: 14,
    bottom: 16,
    zIndex: 18,
    elevation: 24,
  },
  sidebarCard: {
    flex: 1,
    borderRadius: 36,
    backgroundColor: "rgba(255,255,255,0.9)",
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 16,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: palette.shadow,
    shadowOpacity: 0.1,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  sidebarTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  sidebarCloseButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
  },
  sidebarTopLabel: {
    color: palette.textTertiary,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  sidebarTopTitle: {
    marginTop: 4,
    color: palette.textPrimary,
    fontSize: 20,
    fontWeight: "800",
  },
  sidebarProfileCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 24,
    backgroundColor: palette.surface,
    padding: 14,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: palette.shadow,
    shadowOpacity: 0.05,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  sidebarProfileTextWrap: {
    flex: 1,
  },
  sidebarProfileName: {
    color: palette.textPrimary,
    fontSize: 16,
    fontWeight: "800",
  },
  sidebarProfileSubText: {
    marginTop: 5,
    color: palette.textSecondary,
    fontSize: 11,
    lineHeight: 18,
  },
  sidebarSectionHeader: {
    marginTop: 20,
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sidebarSectionTitle: {
    color: palette.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  sidebarSectionSubText: {
    color: palette.textTertiary,
    fontSize: 12,
    fontWeight: "700",
  },
  sidebarSpaceList: {
    flex: 1,
  },
  sidebarSpaceListContent: {
    gap: 10,
    paddingBottom: 6,
  },
  sidebarEmptyCard: {
    borderRadius: 20,
    backgroundColor: palette.surfaceSoft,
    paddingHorizontal: 14,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: palette.border,
  },
  sidebarEmptyText: {
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  sidebarSpaceCard: {
    borderRadius: 24,
    backgroundColor: palette.surface,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: palette.border,
  },
  sidebarSpaceCardActive: {
    backgroundColor: palette.surfaceMuted,
    borderColor: palette.borderStrong,
    shadowColor: palette.shadow,
    shadowOpacity: 0.05,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  sidebarSpaceTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  sidebarSpaceName: {
    flex: 1,
    color: palette.textPrimary,
    fontSize: 14,
    fontWeight: "800",
  },
  sidebarSpaceNameActive: {
    color: palette.textPrimary,
  },
  sidebarSpaceActiveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: palette.success,
  },
  sidebarSpaceCode: {
    marginTop: 7,
    color: palette.textTertiary,
    fontSize: 10,
  },
  sidebarSpaceCodeActive: {
    color: palette.textSecondary,
  },
  sidebarSpaceMeta: {
    marginTop: 8,
    color: palette.textTertiary,
    fontSize: 10,
    lineHeight: 16,
  },
  sidebarSpaceMetaActive: {
    color: palette.textSecondary,
  },
  sidebarBottomActions: {
    marginTop: 16,
    gap: 10,
    flexDirection: "column",
  },
  sidebarCreateButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 18,
    backgroundColor: palette.accent,
    paddingVertical: 13,
    shadowColor: palette.accent,
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  sidebarCreateButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  sidebarJoinButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 18,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.accentSoftBorder,
    paddingVertical: 13,
  },
  sidebarJoinButtonText: {
    color: palette.textSecondary,
    fontSize: 14,
    fontWeight: "700",
  },
  avatarFallback: {
    backgroundColor: palette.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarFallbackText: {
    color: "#FFFFFF",
    fontWeight: "800",
  },
  dialogMask: {
    flex: 1,
    backgroundColor: "rgba(17,20,17,0.24)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 22,
  },
  dialogBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  dialogCard: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 26,
    backgroundColor: "rgba(255,255,255,0.98)",
    padding: 18,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: palette.shadow,
    shadowOpacity: 0.12,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 16 },
    elevation: 10,
  },
  dialogHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  dialogTitleWrap: {
    flex: 1,
  },
  dialogTitle: {
    color: palette.textPrimary,
    fontSize: 20,
    fontWeight: "800",
  },
  dialogDescription: {
    marginTop: 8,
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  dialogClose: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: "center",
    justifyContent: "center",
  },
  dialogBody: {
    marginTop: 16,
  },
  dialogFooter: {
    marginTop: 16,
  },
  dialogInput: {
    borderRadius: 18,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: palette.textPrimary,
    fontSize: 15,
  },
  dialogReadonlyInput: {
    fontWeight: "700",
    color: palette.accentStrong,
  },
  dialogActionRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  dialogGhostButton: {
    borderRadius: 16,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.accentSoftBorder,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  dialogGhostButtonText: {
    color: palette.textSecondary,
    fontSize: 14,
    fontWeight: "700",
  },
  dialogPrimaryButton: {
    borderRadius: 16,
    backgroundColor: palette.accent,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: palette.accent,
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  dialogPrimaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  spaceMenuMask: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(22,36,28,0.18)",
  },
  spaceMenuBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  spaceMenuSheet: {
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    backgroundColor: "rgba(255,255,255,0.985)",
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 22,
    borderTopWidth: 1,
    borderColor: palette.border,
    shadowColor: palette.shadow,
    shadowOpacity: 0.14,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: -10 },
    elevation: 16,
  },
  spaceMenuHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  spaceMenuTitle: {
    color: palette.textPrimary,
    fontSize: 17,
    fontWeight: "800",
  },
  spaceMenuCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: palette.shadow,
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  spaceMenuList: {
    gap: 10,
  },
  spaceMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 20,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 15,
    shadowColor: palette.shadow,
    shadowOpacity: 0.05,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 2,
  },
  spaceMenuItemWarn: {
    backgroundColor: "#FFF8F1",
    borderColor: "rgba(249,115,22,0.18)",
  },
  spaceMenuItemDanger: {
    backgroundColor: "#FFF5F5",
    borderColor: "rgba(239,68,68,0.18)",
  },
  spaceMenuIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: "center",
    justifyContent: "center",
  },
  spaceMenuIconWrapWarn: {
    backgroundColor: "#FFF3E8",
    borderColor: "rgba(249,115,22,0.14)",
  },
  spaceMenuIconWrapDanger: {
    backgroundColor: "#FFF1F2",
    borderColor: "rgba(239,68,68,0.14)",
  },
  spaceMenuTextWrap: {
    flex: 1,
  },
  spaceMenuItemTitle: {
    color: palette.textPrimary,
    fontSize: 15,
    fontWeight: "800",
  },
  spaceMenuItemTitleWarn: {
    color: "#EA580C",
  },
  spaceMenuItemTitleDanger: {
    color: palette.danger,
  },
  spaceMenuItemDescription: {
    marginTop: 4,
    color: palette.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  sheetMask: {
    flex: 1,
    backgroundColor: "rgba(17,20,17,0.22)",
    justifyContent: "flex-end",
  },
  sheetKeyboardWrap: {
    flex: 1,
    justifyContent: "flex-end",
  },
  sheetCard: {
    width: "100%",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: "rgba(255,255,255,0.98)",
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 18,
    borderTopWidth: 1,
    borderColor: palette.border,
  },
  publishSheet: {
    minHeight: 480,
    height: "84%",
  },
  editorSheet: {
    minHeight: 360,
    maxHeight: "68%",
  },
  sheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  sheetTitle: {
    color: palette.textPrimary,
    fontSize: 21,
    fontWeight: "800",
  },
  sheetCloseButton: {
    borderRadius: 999,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.accentSoftBorder,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  sheetCloseButtonText: {
    color: palette.textSecondary,
    fontSize: 12,
    fontWeight: "700",
  },
  sheetBody: {
    flex: 1,
    marginTop: 14,
  },
  sheetBodyContent: {
    gap: 14,
    paddingBottom: 8,
  },
  selectImageButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.accentSoftBorder,
    paddingVertical: 13,
    backgroundColor: palette.surface,
  },
  selectImageButtonText: {
    color: palette.textSecondary,
    fontSize: 14,
    fontWeight: "700",
  },
  sheetPreviewCard: {
    borderRadius: 18,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 12,
  },
  sheetPreviewTitle: {
    color: palette.textSecondary,
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 10,
  },
  sheetEmptyCard: {
    borderRadius: 18,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 14,
    paddingVertical: 16,
  },
  sheetEmptyText: {
    color: palette.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  composerInput: {
    minHeight: 170,
    maxHeight: 260,
    borderRadius: 18,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: palette.textPrimary,
    fontSize: 14,
  },
  sheetFooter: {
    paddingTop: 12,
  },
  sheetPrimaryButton: {
    borderRadius: 18,
    backgroundColor: palette.accent,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    shadowColor: palette.accent,
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  sheetPrimaryButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
  },
  disabledButton: {
    opacity: 0.6,
  },
  selectedImageCard: {
    marginRight: 12,
    alignItems: "center",
  },
  selectedImage: {
    width: 84,
    height: 84,
    borderRadius: 14,
    backgroundColor: palette.surfaceMuted,
  },
  selectedImageRemove: {
    marginTop: 8,
    borderRadius: 999,
    backgroundColor: palette.danger,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  selectedImageRemoveText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "800",
  },
  editorCaptionCard: {
    marginTop: 14,
    borderRadius: 18,
    backgroundColor: palette.surfaceSoft,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 14,
  },
  editorCaptionLabel: {
    color: palette.textTertiary,
    fontSize: 12,
    fontWeight: "700",
  },
  editorCaptionText: {
    marginTop: 8,
    color: palette.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  previewMask: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.92)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  previewClose: {
    position: "absolute",
    top: 64,
    right: 18,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.15)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    zIndex: 2,
  },
  previewCloseText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
  },
  previewImage: {
    width: "100%",
    height: "66%",
    borderRadius: 18,
    backgroundColor: "#222C39",
  },
  previewActionRow: {
    marginTop: 18,
    width: "100%",
  },
  previewSaveButton: {
    borderRadius: 16,
    backgroundColor: palette.success,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    shadowColor: palette.success,
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  previewSaveButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
});
